sudo: false
language: node_js
notifications:
  email: false
node_js:
  - 6
  - 8
matrix:
  fast_finish: true
env:
  matrix:
    - ES_VERSION=2.3.4
jdk:
  - oraclejdk8
install:
  - mkdir /tmp/elasticsearch
  - wget -O - https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/${ES_VERSION}/elasticsearch-${ES_VERSION}.tar.gz | tar xz --directory=/tmp/elasticsearch --strip-components=1
  - /tmp/elasticsearch/bin/plugin install analysis-icu
  - /tmp/elasticsearch/bin/elasticsearch --daemonize --path.data /tmp
  - npm i
script:
  - npm run travis
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - npm i -g npm
before_script:
  - sleep 10
  - curl http://127.0.0.1:9200/
  - node scripts/create_index.js -y
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
