language: node_js
dist: bionic
notifications:
  email: false
node_js:
  - 10
  - 12
matrix:
  fast_finish: true
env:
  matrix:
    - ES_VERSION=5.6.12 ES_TYPE=doc JDK_VERSION=oraclejdk8
    - ES_VERSION=5.6.12 ES_TYPE=doc JDK_VERSION=oraclejdk11
    - ES_VERSION=6.8.4 ES_TYPE=doc JDK_VERSION=oraclejdk8
    - ES_VERSION=6.8.4 ES_TYPE=doc JDK_VERSION=oraclejdk11
    - ES_VERSION=6.8.4 ES_TYPE=_doc JDK_VERSION=oraclejdk8
    - ES_VERSION=6.8.4 ES_TYPE=_doc JDK_VERSION=oraclejdk11
jdk:
  - oraclejdk8
  - oraclejdk11
install:
  - ./scripts/setup_ci.sh
  - npm i
script:
  - npm run travis
before_install:
  - npm i -g npm
before_script:
  - curl http://127.0.0.1:9200/
  - ./bin/create_index
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
jobs:
  include:
    - stage: release
      node_js: 12
      script: curl "https://raw.githubusercontent.com/pelias/ci-tools/master/semantic-release.sh" | bash -
      if: (branch = master) AND ( type = push )
