name: 'Continuous Integration'
on:
  push:
    branches-ignore:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  unit-tests:
    uses: ./.github/workflows/_unit_tests.yml
  integration-tests:
    uses: ./.github/workflows/_integration_tests.yml
  npm-publish:
    needs: [unit-tests, integration-tests]
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ${{ vars.UBUNTU_VERSION }}
    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - name: Run semantic-release
      env:
        GH_TOKEN: ${{ secrets.GH_SEMANTIC_RELEASE_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        curl "https://raw.githubusercontent.com/pelias/ci-tools/master/semantic-release.sh" | bash -
  build-docker-images:
    # run this job if the unit tests passed and the npm-publish job was a success or was skipped
    # note: github actions won't run a job if you don't call one of the status check functions, so `always()` is called since it evalutes to `true`
    if: ${{ always() && needs.unit-tests.result == 'success' && (needs.npm-publish.result == 'success' || needs.npm-publish.result == 'skipped') }}
    needs: [unit-tests, integration-tests, npm-publish]
    runs-on: ${{ vars.UBUNTU_VERSION }}
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker images
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          curl "https://raw.githubusercontent.com/pelias/ci-tools/master/build-docker-images.sh" | bash -
